site_name: graph-guard
repo_name: c-fraser/graph-guard
repo_url: https://github.com/c-fraser/graph-guard
site_description: 'Neo4j schema and query validation'
site_author: c-fraser
copyright: 'Copyright &copy; 2023 c-fraser'
nav:
  - graph-guard: index.md
theme:
  name: 'material'
  favicon: favicon.ico
  logo: graph-guard.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: 'blue grey'
    accent: teal
  features:
    - toc.integrate
    - content.code.copy
    - content.code.select
    - navigation.tabs.sticky
extra_css:
  - extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
